In [32]:
import pandas as pd
import numpy as np

# Load the dataset
data = pd.read_csv("ipl_data.csv")
data

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193463,1237181,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,0,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193464,1237181,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193465,1237181,1,13,1,RR Pant,SS Iyer,KH Pandya,0,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
193466,1237181,1,13,2,RR Pant,SS Iyer,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
193467,1237181,1,13,3,SS Iyer,RR Pant,KH Pandya,1,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [33]:
# find the all unique values in data['dismissal_kind']

# data.fielder.unique()

In [34]:
data.isna().sum()

id                       0
inning                   0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
non_boundary             0
is_wicket                0
dismissal_kind      183973
player_dismissed    183973
fielder             186684
extras_type         183235
batting_team             0
bowling_team           191
dtype: int64

In [35]:
#clean the data
data['dismissal_kind'].fillna('not_out', inplace=True)
data['player_dismissed'].fillna('not_dismissed', inplace=True)
data['fielder'].fillna('no_fielder', inplace=True)
data['extras_type'].fillna('no_extras', inplace=True)
data = data.dropna(subset=['bowling_team'])

In [36]:
data.isna().sum()

id                  0
inning              0
over                0
ball                0
batsman             0
non_striker         0
bowler              0
batsman_runs        0
extra_runs          0
total_runs          0
non_boundary        0
is_wicket           0
dismissal_kind      0
player_dismissed    0
fielder             0
extras_type         0
batting_team        0
bowling_team        0
dtype: int64

In [37]:
#convert id to match_id
data.rename(columns={'id':'match_id'}, inplace=True)

/var/folders/d0/ph7mblw52l1gb1c0yy_ld5hc0000gn/T/ipykernel_24626/76854798.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns={'id':'match_id'}, inplace=True)

In [38]:
data

,match_id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,not_out,not_dismissed,no_fielder,no_extras,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193463,1237181,1,12,5,RR Pant,SS Iyer,NM Coulter-Nile,0,0,0,0,0,not_out,not_dismissed,no_fielder,no_extras,Delhi Capitals,Mumbai Indians
193464,1237181,1,12,6,RR Pant,SS Iyer,NM Coulter-Nile,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Delhi Capitals,Mumbai Indians
193465,1237181,1,13,1,RR Pant,SS Iyer,KH Pandya,0,1,1,0,0,not_out,not_dismissed,no_fielder,wides,Delhi Capitals,Mumbai Indians
193466,1237181,1,13,2,RR Pant,SS Iyer,KH Pandya,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Delhi Capitals,Mumbai Indians
193467,1237181,1,13,3,SS Iyer,RR Pant,KH Pandya,1,0,1,0,0,not_out,not_dismissed,no_fielder,no_extras,Delhi Capitals,Mumbai Indians

In [39]:
def player_dismissed_agg(x):
    dismissed_players = x[x != 'not_dismissed']
    if dismissed_players.empty:
        return 'not_dismissed'
    else:
        return list(dismissed_players)

In [40]:
# batsman_stats = data.groupby(['match_id', 'batsman']).agg(
#         runs=pd.NamedAgg(column='batsman_runs', aggfunc='sum'),
#         boundaries=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 4).sum()),
#         sixes=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 6).sum()),
#         balls_faced=pd.NamedAgg(column='ball', aggfunc='count'),
#         # if player_dismissed is not_dismissed then do '' else else player_dismissed
#         dismissed=pd.NamedAgg(column='player_dismissed', 
#                               aggfunc= player_dismissed_agg,
#                               ),)

# batsman_stats

In [41]:
# bowler_stats = data.groupby(['match_id', 'bowler']).agg(
#         wickets=pd.NamedAgg(column='is_wicket', aggfunc='sum'),
#         runs_conceded=pd.NamedAgg(column='total_runs', aggfunc='sum'),
#         balls_bowled=pd.NamedAgg(column='ball', aggfunc='count'),
#         batsman_wicket=pd.NamedAgg(column='player_dismissed', aggfunc=player_dismissed_agg),
#         extras=pd.NamedAgg(column='extras_type', aggfunc=lambda x: (x != 'no_extras').sum() ),
#         sixes_taken=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 6).sum()),
#         boundaries_taken=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 4).sum()),
#         # maidens=pd.NamedAgg(column='over', aggfunc=lambda x: (x['total_runs'] == 0).sum())
#     )
# bowler_stats

In [42]:
data.dismissal_kind.unique()

array(['not_out', 'caught', 'run out', 'bowled', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field'], dtype=object)

In [43]:
# fielder_stats = data.groupby(['match_id', 'fielder']).agg(
#         catches=pd.NamedAgg(column='dismissal_kind', aggfunc=lambda x: (x == 'caught').sum()),
#         stumpings=pd.NamedAgg(column='dismissal_kind', aggfunc=lambda x: (x == 'stumped').sum()),
#         run_outs=pd.NamedAgg(column='dismissal_kind', aggfunc=lambda x: (x == 'run out').sum()),
#     )
# fielder_stats

In [44]:
# player_stats = pd.merge(batsman_stats.reset_index(), bowler_stats.reset_index(), on=['match_id', 'batsman'], how='outer')
# player_stats = pd.merge(player_stats, fielder_stats.reset_index(), left_on=['match_id', 'batsman'], right_on=['match_id', 'fielder'], how='outer')
# player_stats

In [45]:


# Remove any missing or inconsistent values
data.dropna(inplace=True)

# Aggregate data
def aggregate_data(data:pd.DataFrame):
    """
    Aggregate data by calculating the total batting, bowling,
    fielding, and economy rate points for each player.
    """
    # Add code to calculate points based on the given criteria
    # ...
    # import pandas as pd

    # Assuming 'data' is a DataFrame containing the ball-by-ball analysis
    # Calculate runs scored, boundaries, and sixes for each batsman
    batsman_stats = data.groupby(['match_id', 'batsman']).agg(
        runs=pd.NamedAgg(column='batsman_runs', aggfunc='sum'),
        boundaries=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 4).sum()),
        sixes=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 6).sum()),
        balls_faced=pd.NamedAgg(column='ball', aggfunc='count'),)
    # Calculate wickets taken, runs conceded, and maidens bowled for each bowler
    bowler_stats = data.groupby(['match_id', 'bowler']).agg(
        wickets=pd.NamedAgg(column='is_wicket', aggfunc='sum'),
        runs_conceded=pd.NamedAgg(column='total_runs', aggfunc='sum'),
        balls_bowled=pd.NamedAgg(column='ball', aggfunc='count'),
        batsman_wicket=pd.NamedAgg(column='player_dismissed', aggfunc=player_dismissed_agg),
        extras=pd.NamedAgg(column='extras_type', aggfunc=lambda x: (x != 'no_extras').sum() ),
        sixes_taken=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 6).sum()),
        boundaries_taken=pd.NamedAgg(column='batsman_runs', aggfunc=lambda x: (x == 4).sum()),
    )

    # Calculate catches, stumpings, and run-outs for each fielder
    fielder_stats = data.groupby(['match_id', 'fielder']).agg(
        catches=pd.NamedAgg(column='dismissal_kind', aggfunc=lambda x: (x == 'caught').sum()),
        stumpings=pd.NamedAgg(column='dismissal_kind', aggfunc=lambda x: (x == 'stumped').sum()),
        run_outs=pd.NamedAgg(column='dismissal_kind', aggfunc=lambda x: (x == 'run out').sum())
    )
    batsman_reset_index = batsman_stats.reset_index()
    bowler_reset_index = bowler_stats.reset_index()

    # Merge the aggregated stats for batsmen, bowlers, and fielders
    player_stats = pd.merge(batsman_stats.reset_index(), bowler_stats.reset_index(), left_on=['match_id', 'batsman'], right_on=['match_id', 'bowler'], how='outer')

    # Rename columns to avoid ambiguity
    player_stats.rename(columns={'batsman': 'player_batsman', 'bowler': 'player_bowler'}, inplace=True)

    # Combine the player_batsman and player_bowler columns into a single 'player' column
    player_stats['player'] = player_stats['player_batsman'].fillna(player_stats['player_bowler'])
    player_stats.drop(columns=['player_batsman', 'player_bowler'], inplace=True)

    # Merge the player_stats with fielder_stats
    player_stats = pd.merge(player_stats, fielder_stats.reset_index(), left_on=['match_id', 'player'], right_on=['match_id', 'fielder'], how='outer')

    # Rename the 'fielder' column to 'player_fielder' and fill missing values in the 'player' column with 'player_fielder' values
    player_stats.rename(columns={'fielder': 'player_fielder'}, inplace=True)
    player_stats['player'].fillna(player_stats['player_fielder'], inplace=True)
    player_stats.drop(columns=['player_fielder'], inplace=True)


    player_stats.fillna(0, inplace=True)
    # in the player_stats dataframe, the batsman_wicket column convert 0 and not dismissed to no wickets
    player_stats['batsman_wicket'] = player_stats['batsman_wicket'].apply(lambda x: 'No wickets' if x == 'not_dismissed' or x==0 else x)
    return player_stats


# Apply the aggregation function
player_stats = aggregate_data(data)

/var/folders/d0/ph7mblw52l1gb1c0yy_ld5hc0000gn/T/ipykernel_24626/51298895.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [46]:
player_stats.columns

Index(['match_id', 'runs', 'boundaries', 'sixes', 'balls_faced', 'wickets',
       'runs_conceded', 'balls_bowled', 'batsman_wicket', 'extras',
       'sixes_taken', 'boundaries_taken', 'player', 'catches', 'stumpings',
       'run_outs'],
      dtype='object')

In [47]:
# Create features
def create_features(data):
    """
    Create features such as batting average, bowling average,
    strike rate, and economy rate for each player.
    """
    player_stats['strike_rate'] = player_stats.apply(lambda x: (x['runs'] / x['balls_faced']) *     100 if x['balls_faced'] > 0 else 0, axis=1)

    # Calculate bowling average and economy rate
    player_stats['economy_rate'] = player_stats.apply(lambda x: x['runs_conceded'] / (x ['balls_bowled'] / 6) if x['balls_bowled'] > 0 else 0, axis=1)

    return player_stats

# Apply the feature creation function
player_stats =  create_features(data)

# One-hot encode categorical variables
# data = pd.get_dummies(data, columns=["team_name", "player_role"])

In [48]:
# Calculate batting average and strike rate

In [49]:
def strike_rate_points(row):
    if row['balls_faced'] < 10:  # Minimum 10 balls to be played
        return 0
    strike_rate = (row['runs'] / row['balls_faced']) * 100
    if 60 <= strike_rate < 70:
        return -2
    elif 50 <= strike_rate < 59.99:
        return -4
    elif strike_rate < 50:
        return -6
    return 0

# player_stats['strike_rate_points'] = player_stats.apply(strike_rate_points, axis=1)
def economy_rate_points(row):
    if row['balls_bowled'] < 12:  # Minimum 2 overs to be bowled
        return 0
    economy_rate = row['runs_conceded'] / (row['balls_bowled'] / 6)
    if 6 <= economy_rate < 5:
        return 2
    elif 4.99 >= economy_rate >= 4:
        return 4
    return 0




def calculate_points(row):
    points = 0
    # Calculate batting points
    points += row['runs']
    # Add bonus points for boundaries
    points += row['boundaries'] + 2 * row['sixes']
    # Add bonus points for reaching milestones
    if row['runs'] >= 100:
        points += 16
    elif row['runs'] >= 50:
        points += 8
    # Subtract points for ducks
    if row['runs'] == 0 and row['balls_faced'] >= 1:
        points -= 2

    # Calculate bowling points
    points += 25 * row['wickets']
    # Add bonus points for multiple wickets
    if row['wickets'] >= 5:
        points += 16
    elif row['wickets'] >= 4:
        points += 8

    # Add points for maiden overs
    # points += 8 * row['maidens']

    # Calculate fielding points
    points += 8 * row['catches']
    points += 12 * row['stumpings']
    points += 6 * row['run_outs']
    

    #economy rate points
    points += economy_rate_points(row)
    #strike rate points
    points += strike_rate_points(row)
    return points

# Calculate points for each player in each match
player_stats['points'] = player_stats.apply(calculate_points, axis=1)

In [50]:
sorted_on_points = player_stats.sort_values(by=['points'], ascending=True)

In [51]:
type(sorted_on_points)

pandas.core.frame.DataFrame

In [52]:
# #group on players 
player_stats_only = sorted_on_points.groupby(['player']).agg(
    runs=pd.NamedAgg(column='runs', aggfunc='sum'),
    balls_faced=pd.NamedAgg(column='balls_faced', aggfunc='sum'),
    boundaries=pd.NamedAgg(column='boundaries', aggfunc='sum'),
    sixes=pd.NamedAgg(column='sixes', aggfunc='sum'),
    wickets=pd.NamedAgg(column='wickets', aggfunc='sum'),
    balls_bowled=pd.NamedAgg(column='balls_bowled', aggfunc='sum'),
    runs_conceded=pd.NamedAgg(column='runs_conceded', aggfunc='sum'),
    # maidens=pd.NamedAgg(column='maidens', aggfunc='sum'),
    catches=pd.NamedAgg(column='catches', aggfunc='sum'),
    stumpings=pd.NamedAgg(column='stumpings', aggfunc='sum'),
    run_outs=pd.NamedAgg(column='run_outs', aggfunc='sum'),
    points=pd.NamedAgg(column='points', aggfunc='sum')
)
    
# drop if player_stats contains player contains ,
player_stats_only = player_stats_only[~player_stats_only.index.str.contains(",")]

In [53]:
# sort it on balls_faced
player_stats_sorter = player_stats_only.sort_values(by=['boundar'], ascending=False)

In [ ]:
# Normalize data
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()  # or StandardScaler()
data_scaled = scaler.fit_transform(data)

In [ ]:
from sklearn.model_selection import train_test_split

X = data.drop("total_points", axis=1)
y = data["total_points"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# You can choose other models such as Linear Regression, SVM, XGBoost, etc.
model = RandomForestRegressor(n_estimators=100, random_state=42)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 score:", r2)

In [ ]:
from sklearn.model_selection import GridSearchCV

# Set up the hyperparameter grid
param_grid = {
    "n_estimators": [10, 50, 100, 200],
    "max_depth": [None, 10, 20, 30],
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(model, param_grid, cv=5, scoring="neg_mean_absolute_error")
grid_search.fit(X_train, y_train)

# Update the model with the best hyperparameters
model = grid_search.best_estimator_

In [ ]:
importances = model.feature_importances_
feature_importances = pd.DataFrame({"feature": X_train.columns, "importance": importances})
print(feature_importances.sort_values("importance", ascending=False))

In [ ]:
def predict_top_11_players(model, players_data):
    """
    Predict the top 11 players for a match using the trained model.
    """
    # Preprocess the data
    # ...

    # Use the trained model to predict the points for each player
    points_pred = model.predict(players_data)

    # Select the top 11 players based